mp-069: top15 by likes
Pharmazon/gb-music-portal-monolith pull request #75
Opened 2019-07-05 15:12 UTC by alexey-vasyunin

Отдаёт через REST-контроллер по /api/top-tracks 15 треков с наибольшим числом лайков.

2019-07-05 16:08 UTC, Pharmazon commented
Должен быть один коммит

2019-07-05 17:58 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +    @GetMapping("/api/top-tracks")
давай сделаем url /api/miraculous/top/15

2019-07-05 17:59 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/dto/TrackDto.java
>      private String fileLink;
я за то чтобы не отдавать на фронт ссылку на файл, но тогда тебе нужно объяснить Анне как сделать проигрывание через id

2019-07-05 18:04 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/dto/TrackDto.java
> +    private Long groupId;
давай именовать поля типа не groupId, а bandId  в соответствии с названием сущности

2019-07-05 18:06 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/service/like/LikeServiceImpl.java
>      @Autowired
Давай сделаем инжект для всего через конструктор

2019-07-06 07:46 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +    @GetMapping("/api/top-tracks")
Сделал /api/miraculous/top/{max}, где max от 1 до 100, при других значениях будет установлен в 15

2019-07-06 07:47 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/dto/TrackDto.java
> +    private Long groupId;
Помененяно в сответствии с текущей версией DTO

2019-07-06 07:48 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/service/like/LikeServiceImpl.java
>      @Autowired
Сделано через конструктор

2019-07-06 07:49 UTC, alexey-vasyunin commented
Собрано в один коммит

2019-07-06 09:29 UTC, Pharmazon requested changes
Внеси изменения в соответствии с комментариями, под каждый комментарием проставь статус. Не забудь обновить карточку в Trello

2019-07-06 09:29 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +public class TrackController {
RequestMapping c url /api/miraculous/top

2019-07-06 09:29 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/dto/TrackDto.java
> +    private Long liked;
Есть сомнения, что у тебя из базы достается ДТО, у тебя дто соответствуют полям сущности?

2019-07-06 09:29 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/service/like/LikeServiceImpl.java
> +    public void setLikeRepository(LikeRepository likeRepository, TrackRepository trackRepository) {
Давай сделаем инжект через конструктор

2019-07-06 09:41 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +public class TrackController {
Не совсем понял. Вместо GetMapping сделать RequestMapping с указанием на get?

2019-07-06 09:43 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/dto/TrackDto.java
> +    private Long liked;
Из базы не достаются Dto, они же для трансферинга на фронт и у них есть конструктор для преобразования в dto

2019-07-06 09:56 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/service/like/LikeServiceImpl.java
> +    public void setLikeRepository(LikeRepository likeRepository, TrackRepository trackRepository) {
fixed

2019-07-06 09:56 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +public class TrackController {
fixed

2019-07-06 11:44 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +public class TrackController {
Сделано

2019-07-06 11:45 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/service/like/LikeServiceImpl.java
> +    public void setLikeRepository(LikeRepository likeRepository, TrackRepository trackRepository) {
Сделано

2019-07-06 11:45 UTC, alexey-vasyunin commented on backend/src/main/java/ru/geekbrains/musicportal/dto/TrackDto.java
> +    private Long liked;
Соответствуют. Сделано

2019-07-06 13:38 UTC, Pharmazon requested changes
Внеси изменения в соответствии с комментариями, под каждый комментарием проставь статус. Не забудь обновить карточку в Trello

2019-07-06 13:38 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +@RestController
Добавь сюда @CrossOrigin

2019-07-06 13:38 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +@RestController
к руту контроллера над классом пишешь RequestMapping
а над методами пишешь GetMapping (Post, Put, Delete)

2019-07-06 13:38 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +public class TrackController {
к руту контроллера над классом пишешь RequestMapping
а над методами пишешь GetMapping (Post, Put, Delete)

2019-07-06 13:38 UTC, Pharmazon commented on backend/src/main/java/ru/geekbrains/musicportal/controller/TrackController.java
> +    @RequestMapping(value = "/api/miraculous/top/{max}", method = RequestMethod.GET)
к руту контроллера над классом пишешь RequestMapping
а над методами пишешь GetMapping (Post, Put, Delete)

2019-07-08 05:10 UTC, Pharmazon commented
Лучше создать новую ветку

2019-07-08 05:10 UTC, closed without merging